apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations:
    argocd-image-updater.argoproj.io/image-list: nginx=jgnunes12/k3s-lab
    argocd-image-updater.argoproj.io/nginx.update-strategy: newest-build
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: jgnunes12/k3s-lab:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
