apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:8
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: jgnunes12/k3s-lab: v1.20
        imagePullPolicy: Always
        ports:
        - containerPort: 80
